apiVersion : apps/v1
kind: Deployment
metadata:
  name: "expressazure-010a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "expressazure-010a"
  template:
    metadata:
      labels:
        app: "expressazure-010a"
    spec:
      containers:
        - name: "expressazure-010a"
          image: "887eccb0ccc54936b06995fa941e2237.azurecr.io/expressazure"
          ports:
          - containerPort: 80